### ISSUE TITLE
Update javadoc plugin to 3.0.0 to support Java 9

### ISSUE THREAD

**Issue by bruceskingle** [symphonyoss/ssf-parent-pom#4]
The version of the maven javadoc plugin specified here does not work with Java9. The current version, 3.0.0 does seem to work. The version can be overridden in the pom of individual projects, but I think we should update the one here to 3.0.0

**Comment by maoo** [comment]
Version 10-SNAPSHOT just deployed and version 10 released (will take a couple of hours to be available on Maven Central)

**Comment by maoo** [comment]
Version 11 released, marking issue as closed - http://search.maven.org/#artifactdetails%7Corg.symphonyoss%7Csymphonyoss%7C11%7Cpom
